### ISSUE TITLE
Immediate failure to repair game (issue may be heroic-gogdl's fault)

### ISSUE THREAD

**Issue by instinctualjealousy** [hawkeye116477/playnite-gog-oss-plugin#14]
### Prerequisites

- [X] I've looked through [existing issues](https://github.com/hawkeye116477/playnite-gog-oss-plugin/issues) to make sure that this bug hasn't been reported before.
- [X] I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines) and know netiquette.

### Playnite version

10.34.0.23368

### Plugin version

1.0.3.27564

### Comet version

0.1.2

### Gogdl version

1.1.2

### Bug description

Immediate failure upon calling a repair operation on a GOG OSS managed game. This is 100% replicable on my setup, regardless of game or game state. I am having other issues (Heroic-Games-Launcher/heroic-gogdl#57) with heroic-gogdl that I simply don't understand, however- so this might be a red herring and not the fault of your plugin.

I'm managing my gogdl and Comet installs with scoop manifests:
https://github.com/instinctualjealousy/holes/blob/master/bucket/gogdl.json
https://github.com/instinctualjealousy/holes/blob/master/bucket/gog-comet.json
https://github.com/instinctualjealousy/holes/blob/master/bucket/gog-comet-dummyservice.json

I don't think I've somehow broken anything myself, and I don't think my existing Python environment/configuration should be affecting compiled standalone Python programs...

### Relevant log

A result from a test yesterday:
```
11-11 21:51:12.679|DEBUG|GogOssLibrary#CliWrapCommandExtensions:Executing command: C:\Users\Adam\scoop\apps\gogdl\current\gogdl_windows_x86_64.exe --auth-config-path C:\Users\Adam\AppData\Roaming\Playnite\ExtensionsData\03689811-3f33-4dfb-a121-2ee168fb9a5c\tokens.json repair 1207659238 --path "D:\GOGLibrary\Pandemonium 2\\" --build 48254350742780019 --platform windows --skip-dlcs
11-11 21:51:14.213|ERROR|GogOssLibrary#GogOssDownloadManagerView:TypeError: expected str, bytes or os.PathLike object, not NoneType
11-11 21:51:14.213|ERROR|GogOssLibrary#GogOssDownloadManagerView:[PYI-11908:ERROR] Failed to execute script 'cli' due to unhandled exception!
```

A result from today (lack of specific cause, path that doesn't require quoting):
```
13-11 10:10:28.343|DEBUG|GogOssLibrary#CliWrapCommandExtensions:Executing command: C:\Users\Adam\scoop\apps\gogdl\current\gogdl_windows_x86_64.exe --auth-config-path C:\Users\Adam\AppData\Roaming\Playnite\ExtensionsData\03689811-3f33-4dfb-a121-2ee168fb9a5c\tokens.json repair 1207658920 --path D:\GOGLibrary\XIII\ --max-workers 4 --build 52687138117587901 --lang en-US --platform windows --skip-dlcs
13-11 10:10:28.797|ERROR|GogOssLibrary#GogOssDownloadManagerView:[PYI-10680:ERROR] Failed to execute script 'cli' due to unhandled exception!
```

**Comment by hawkeye116477** [comment]
[GogOssLibrary_1_0_3_33235.pext.zip](https://github.com/user-attachments/files/17754028/GogOssLibrary_1_0_3_33235.pext.zip)

Here's workaround for multiprocessing error, jsut remove .zip from filename and drag and drop to Playnite's window. In case of other errors, I can't reproduce them.

**Comment by hawkeye116477** [comment]
Ok. I published updates. From your full log looks like that other errors are caused by gogdl itself, like it can't download something.
