### ISSUE TITLE
Playtime stats not imported from GOG

### ISSUE THREAD

**Issue by Clusters** [hawkeye116477/playnite-gog-oss-plugin#15]
### Prerequisites

- [X] I've looked through [existing issues](https://github.com/hawkeye116477/playnite-gog-oss-plugin/issues) to make sure that this bug hasn't been reported before.
- [X] I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines) and know netiquette.

### Playnite version

10.34.0.23368

### Plugin version

1.0.3.27564

### Comet version

0.1.2

### Gogdl version

1.1.2

### Bug description

I have set the setting to import playtime stats inside Playnites settings to "new and existing" games. Steam integration imports the playstats without any issues. But with GOG OSS it seems not possible?

The game I particular check for any playtime data imports is "The Witcher 3 - Complete Edition"

### Relevant log

No relevant logs can be observed, however, some games can not be found.
e.g.
|WARN |GogOssLibrary#GogMetadataProvider:Failed to get store data from page, no data found. https://www.gog.com/en/game/doom_3_classic

**Comment by hawkeye116477** [comment]
You need to check sync playtime in plugin's settings, otherwise won't import.

**Comment by Clusters** [comment]
Thanks a lot for the fast reply!
I now know what the problem was. The scrolling did not work in the Integrations settings page (it still doesn't). Therefore I wasn't aware of the whole "Cloud" section. 
Not sure if this is a settings page issue or a Playnite issue though.
With Steam Integration it also only working for the Metadata settings tab. The other tabs can't scroll either.

**Comment by hawkeye116477** [comment]
> The scrolling did not work in the Integrations settings page (it still doesn't). Therefore I wasn't aware of the whole "Cloud" section.

I didn't suppose that scrolling is needed for that. It's fully displayed at my screen, but perhaps I've too big screen :smile:.
I'll wrap it in ScrollViewer, which should fix problem.

**Comment by Clusters** [comment]
Nice work! Thanks again! Much appreciated :)
