### ISSUE TITLE
Utilization of /galaxyclient flag on scriptinterpreter/supportExe leads to broken game shortcuts for Galaxy-expecting games if there is no installation of GOG Galaxy

### ISSUE THREAD

**Issue by instinctualjealousy** [hawkeye116477/playnite-gog-oss-plugin#21]
### Prerequisites

- [X] I've looked through [existing issues](https://github.com/hawkeye116477/playnite-gog-oss-plugin/issues) to make sure that this bug hasn't been reported before.
- [X] I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines) and know netiquette.

### Playnite version

10.34.0.23368

### Plugin version

1.0.4.32868 (Haven't updated as I'm waiting for my download queue to finish)

### Comet version

0.1.2

### Gogdl version

1.1.2

### Bug description

Within scriptinterpreter's install script, it seems to be looking to the registry (`HKLM\SOFTWARE\GOG.com\GalaxyClient`?) to find Galaxy's install path to populate the generated shortcuts with. If the path doesn't exist, you simply end up with shortcuts that don't point to an executable, and in my case, target the root of `C:\`!

I'm unsure if using /galaxyclient is really a useful default in any situation. Without the flag, it simply creates direct shortcuts which at the very least wouldn't be broken but would bypass Playnite and Comet. I'd rather no shortcuts at all as a plugin option, but I'm not sure if scriptinterpreter as compiled has such an argument to pass.

### Relevant log

See attached screenshot.

### Screenshots

![image](https://github.com/user-attachments/assets/0739de3d-53d1-455b-816f-70517dd800aa)

**Comment by hawkeye116477** [comment]
> I'd rather no shortcuts at all as a plugin option, but I'm not sure if scriptinterpreter as compiled has such an argument to pass.

There are no desktop shortcuts, flag is passed to disable creating them.

**Comment by instinctualjealousy** [comment]
Not desktop shortcuts:
![image](https://github.com/user-attachments/assets/b112a286-1625-4060-8463-9fe444e56c95)

**Comment by hawkeye116477** [comment]
Ah, so you mean shortcuts at Start Menu. I didn't noticed that they exists even and indeed they are broken :smile:.
