### ISSUE TITLE
Not all routines in goggame-*.script being ran

### ISSUE THREAD

**Issue by instinctualjealousy** [hawkeye116477/playnite-gog-oss-plugin#25]
### Prerequisites

- [X] I've looked through [existing issues](https://github.com/hawkeye116477/playnite-gog-oss-plugin/issues) to make sure that this bug hasn't been reported before.
- [X] I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines) and know netiquette.

### Playnite version

10.34.0.23368

### Plugin version

1.1.2.35338

### Comet version

0.1.2

### Gogdl version

1.1.2

### Bug description

All of my games are clean installs without any heroic-gogdl, Playnite or registry leftovers beforehand- and this is after finalizing the installations with the newest plugin version (I downloaded with an earlier version).

I spotted this on DOSBox games due to the DOSBOXCONF files that are supposed to be in the game's root. Neither Screamer nor Theme Park will start for me because they're missing at the expected location. DOSBox runs and immediately closes with nothing to do. I can confirm the DOSBox registry entries were written.

Crime Cities crashes on startup, and I think it might be related to files not being copied as well.

I can find other examples of `"source": "{supportDir}/app", "target": "{app}"` routines failing, but for the sake of levity I'm not going to reference all I've found. Also, I'm sure you know that `{app}` means game root.

I think most, if not all of the other routines are working. Even the creation routine for generating a `cloud_saves` folder at the root for DOSBox games seems to be working, and I believe the registry routines are all working, too. It might be good to give this all a onceover though, as the means of failure may not be terribly specific to a particular routine.

### Relevant log

Theme Park: [goggame-1207660423.json](https://github.com/user-attachments/files/17849859/goggame-1207660423.json)
Crime Cities: [goggame-1485600994.json](https://github.com/user-attachments/files/17849871/goggame-1485600994.json)
(Renamed ext for upload)

### Screenshots

Theme Park:
![image](https://github.com/user-attachments/assets/60d10bb5-cb92-4750-8640-15af2f5f2a72)
![image](https://github.com/user-attachments/assets/9e55064d-368c-4f86-9edf-cc5c108f4669)

Crime Cities:
![image](https://github.com/user-attachments/assets/e1a70ac4-de98-4198-be96-a5b73a76ec45)
![image](https://github.com/user-attachments/assets/96df1adc-d424-4f67-b6a2-850b30c56657)

**Comment by hawkeye116477** [comment]
So I've bad news for you, looks like `/galaxyclient` flag needs to be remain, cuz otherwise that happens :smile:.

**Comment by instinctualjealousy** [comment]
That's so silly and awful. These support additions are needed regardless of whether Galaxy is being used. No matter- I made a script to clean up my shortcuts. Sorry about misguiding you.

P.S.: Could you add a menu item to initiate finalizing installation on demand, so I can fix my 24 installed games easily when you push the next update? That or a meta button in the plugin options to do every GOG OSS installed game...

**Comment by hawkeye116477** [comment]
> P.S.: Could you add a menu item to initiate finalizing installation on demand, so I can fix my 24 installed games easily when you push the next update? That or a meta button in the plugin options to do every GOG OSS installed game...

You can select these games with ctrl key and click to repair and then after you launch them next time, there will be "completing installation".

**Comment by instinctualjealousy** [comment]
Good to know, thanks. I didn't want to touch the repair function with a ten-foot pole because of heroic-gogdl's failures. If repair throws an error, will it still set them up for finalizing installation, or will it break and not attempt anything further?

Also, since I'm always in a hurry to do everything, I just threw together a *.bat by heavily filtering out the log for the actual commands and appending /galaxyclient back to all of them and running it. Hahaha. Indeed, the support files are fixed. So silly.
