### ISSUE TITLE
gog oss won't  download games.

### ISSUE THREAD

**Issue by mando7350** [hawkeye116477/playnite-gog-oss-plugin#28]
### Prerequisites

- [X] I've looked through [existing issues](https://github.com/hawkeye116477/playnite-gog-oss-plugin/issues) to make sure that this bug hasn't been reported before.
- [X] I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines) and know netiquette.

### Playnite version

10.34.0.23368

### Plugin version

1.1.3.37895

### Comet version

0.1.2

### Gogdl version

1.1.2

### Bug description

![gog oss](https://github.com/user-attachments/assets/066d70f6-4b2e-4e71-958f-e10747d19f4e)

### Relevant log

[gog log error.zip](https://github.com/user-attachments/files/17891675/gog.log.error.zip)

### Screenshots

![gog oss](https://github.com/user-attachments/assets/de24d63a-584a-46bc-9c0c-61b07390dac1)

**Comment by hawkeye116477** [comment]
@thescarydoor1 Is that happens will all games or only specific ones?

**Comment by hawkeye116477** [comment]
Ok, should be fixed in new update.

**Comment by thescarydoor1** [comment]
Worked, thanks!
