### ISSUE TITLE
Freedom Fighters' Profiles *.dat being reverted to cloud version even if local is newer

### ISSUE THREAD

**Issue by instinctualjealousy** [hawkeye116477/playnite-gog-oss-plugin#31]
### Prerequisites

- [X] I've looked through [existing issues](https://github.com/hawkeye116477/playnite-gog-oss-plugin/issues) to make sure that this bug hasn't been reported before.
- [X] I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines) and know netiquette.

### Playnite version

10.34.0.23368

### Plugin version

1.1.4.22553

### Comet version

0.1.2

### Gogdl version

1.1.2

### Bug description

I can see there is sound logic for handling whether to upload or download, and it's working correctly for the files at the root of the folder (freedom.ini and Keyboard.cfg), but the GogOssCloud log doesn't mention the Profiles folder or its containing Adam.dat and is acting on it anyway, reverting the save to the 2021 version. I'm suspicious this has something to do with subdir handling.

### Relevant log

Filtered log from today's operation:
```
29-11 11:07:21.424|WARN |GogOssLibrary#GogOssCloud:Skipping download, cuz 'C:\Users\Adam\AppData\Roaming\IO Interactive\Freedom Fighters\Keyboard.cfg' file with same date is already available.
29-11 11:07:21.989|WARN |GogOssLibrary#GogOssCloud:Skipping download, cuz 'C:\Users\Adam\AppData\Roaming\IO Interactive\Freedom Fighters\freedom.ini' file with same date is already available.
29-11 11:08:17.496|WARN |GogOssLibrary#GogOssCloud:Skipping upload, cuz identical 'saves/freedom.ini' file is already in the cloud.
29-11 11:08:17.504|WARN |GogOssLibrary#GogOssCloud:Skipping upload, cuz 'saves/Keyboard.cfg' file in the cloud is newer.
```

### Screenshots

![image](https://github.com/user-attachments/assets/2c0d2990-5c91-4d0d-91fe-b8bb62da82e6)
![image](https://github.com/user-attachments/assets/24eb5c4a-7433-41a0-b8c8-cc93e869bf81)

**Comment by hawkeye116477** [comment]
Can you show screenshoot from https://www.gog.com/account/cloud-saves/ after you click to manage near Freedom fighters?

**Comment by instinctualjealousy** [comment]
![image](https://github.com/user-attachments/assets/10eb0667-8f36-4614-aac9-61bed83fa07c)

**Comment by hawkeye116477** [comment]
Ok, remove `.zip` from attached file's name and let me know if that's fixed.
[GogOssLibrary_1_1_4_36748.pext.zip](https://github.com/user-attachments/files/17997913/GogOssLibrary_1_1_4_36748.pext.zip)

**Comment by instinctualjealousy** [comment]
It now logs it:
```
03-12 14:04:35.618|WARN |GogOssLibrary#GogOssCloud:Skipping upload, cuz identical 'saves/freedom.ini' file is already in the cloud.
03-12 14:04:35.627|WARN |GogOssLibrary#GogOssCloud:Skipping upload, cuz 'saves/Keyboard.cfg' file in the cloud is newer.
03-12 14:04:35.627|WARN |GogOssLibrary#GogOssCloud:Skipping upload, cuz 'saves/Profiles/Adam.dat' file in the cloud is newer.
```
It thinks the 2021 file is newer than the 2024 file and loses my progress again.

**Comment by hawkeye116477** [comment]
Hmm, no idea what's wrong here then. Please try new build and show me logs, now should be more detailed, so we'll know what's up :smile:.
[NileLibrary_1_1_1_39631.pext.zip](https://github.com/user-attachments/files/17999070/NileLibrary_1_1_1_39631.pext.zip)

**Comment by instinctualjealousy** [comment]
You accidentally sent me a Nile WIP build there!

**Comment by hawkeye116477** [comment]
Ah, right, sorry, fixed.

**Comment by instinctualjealousy** [comment]
The startup:
```
03-12 20:55:51.341|DEBUG|GogOssLibrary#GogOssCloud:saves/Keyboard.cfg -- 2024-11-20T20:58:40.507200+00:00 -- 1732136320
03-12 20:55:51.342|DEBUG|GogOssLibrary#GogOssCloud:saves/Profiles/Adam.dat -- 2021-11-14T02:15:01.660970+00:00 -- 1636856101
03-12 20:55:51.342|DEBUG|GogOssLibrary#GogOssCloud:saves/freedom.ini -- 2024-11-27T23:42:22.714920+00:00 -- 1732750942
03-12 20:55:51.342|DEBUG|GogOssLibrary#GogOssCloud:saves/freedom.ini -- 2024-11-27T22:49:08.6275145Z -- 1732747748
03-12 20:55:51.342|DEBUG|GogOssLibrary#GogOssCloud:saves/Keyboard.cfg -- 2023-11-26T22:31:48.1076579Z -- 1701037908
03-12 20:55:51.342|DEBUG|GogOssLibrary#GogOssCloud:saves/Profiles/Adam.dat -- 2024-11-27T23:40:36.4263813Z -- 1732750836
03-12 20:55:51.655|WARN |GogOssLibrary#GogOssCloud:Skipping download, cuz 'C:\Users\Adam\AppData\Roaming\IO Interactive\Freedom Fighters\Keyboard.cfg' file with same date is already available.
03-12 20:55:52.275|WARN |GogOssLibrary#GogOssCloud:Skipping download, cuz 'C:\Users\Adam\AppData\Roaming\IO Interactive\Freedom Fighters\freedom.ini' file with same date is already available.
```
The shutdown:
```
03-12 20:55:57.722|DEBUG|GogOssLibrary#GogOssCloud:saves/Keyboard.cfg -- 2024-11-20T20:58:40.507200+00:00 -- 1732136320
03-12 20:55:57.722|DEBUG|GogOssLibrary#GogOssCloud:saves/Profiles/Adam.dat -- 2021-11-14T02:15:01.660970+00:00 -- 1636856101
03-12 20:55:57.722|DEBUG|GogOssLibrary#GogOssCloud:saves/freedom.ini -- 2024-11-27T23:42:22.714920+00:00 -- 1732750942
03-12 20:55:57.722|DEBUG|GogOssLibrary#GogOssCloud:saves/freedom.ini -- 2024-11-27T22:49:08.6275145Z -- 1732747748
03-12 20:55:57.722|DEBUG|GogOssLibrary#GogOssCloud:saves/Keyboard.cfg -- 2023-11-26T22:31:48.1076579Z -- 1701037908
03-12 20:55:57.722|DEBUG|GogOssLibrary#GogOssCloud:saves/Profiles/Adam.dat -- 2021-11-14T02:12:07.0000000Z -- 1636855927
03-12 20:55:57.722|WARN |GogOssLibrary#GogOssCloud:Skipping upload, cuz 'saves/freedom.ini' file in the cloud is newer.
03-12 20:55:57.722|WARN |GogOssLibrary#GogOssCloud:Skipping upload, cuz 'saves/Keyboard.cfg' file in the cloud is newer.
03-12 20:55:57.722|WARN |GogOssLibrary#GogOssCloud:Skipping upload, cuz 'saves/Profiles/Adam.dat' file in the cloud is newer.
```
Adam.dat is still reverted to 2021 cloud version with this output.

**Comment by hawkeye116477** [comment]
Ok, I think that I tracked down the problem.
[GogOssLibrary_1_1_4_28708.pext.zip](https://github.com/user-attachments/files/18010163/GogOssLibrary_1_1_4_28708.pext.zip)

**Comment by instinctualjealousy** [comment]
Success:
![image](https://github.com/user-attachments/assets/32e2c02f-2097-44e9-ad3a-bdde079dc342)
