### ISSUE TITLE
Sloppily reported issue: I'm suspicious GOG Redistributable download queueing isn't working 100% correctly

### ISSUE THREAD

**Issue by instinctualjealousy** [hawkeye116477/playnite-gog-oss-plugin#32]
### Prerequisites

- [X] I've looked through [existing issues](https://github.com/hawkeye116477/playnite-gog-oss-plugin/issues) to make sure that this bug hasn't been reported before.
- [X] I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines) and know netiquette.

### Playnite version

10.34.0.23368

### Plugin version

1.0.4.32868 (The version I believe I was using when I encountered this issue)

### Comet version

0.1.2

### Gogdl version

1.1.2

### Bug description

I redownloaded all of my games from scratch over a week ago (noted in an earlier issue). I noticed after completion, there were only two redists plus ISI in the `.gogRedist` folder, even though all games in sum had more than that listed. The `installedDepends.json` listed a couple more that didn't actually exist (some other MSVC I believe?). It also didn't list near the total sum for `installed.json` or much of what was in the actual game manifests. I understand that some dependencies like DOSBox and nGlide aren't kept in the redistributable folder, but this didn't make up for the difference.

Still, another behavior that is objectively true is the can-kicking of GOG Redistributables down the queue with the addition of each new game. I think something may be going wrong during the can-kick. Armchair "developer" me thinks it would be preferable to keep it per-game, pre-game (it's already pre-game until you add another to queue, then it's pre-new game), so each game individually has its needs met on demand so they can be started/finalized after an early completion in a queue yet to finish.

To prevent weird queueing edge cases that could occur from manual user interventions and to make the queue less cluttered, GOG Redistributables could be hidden and prepended to the existing game entries instead of discretely listed, but I don't know how easy or hard it'd be to calculate total download size for the progress bar to do it this way or what other complications could occur.

I apologize that I don't have more data to share- I had other, more important issues to file, didn't want to blow you up with more issues, and decided to fix it manually once I understood how everything worked enough to fix it. I also wasn't, and still am not, 100% sure if there is an issue or I'm misinterpreting it as a bystander who doesn't know how the sausage is made.

### Relevant log

Filtered log from the 19th, not sure of full context, but this was before any attempts at manual "fixing", I'm sure:
```
19-11 09:55:01.697|DEBUG|GogOssLibrary#CliWrapCommandExtensions:Executing command: C:\Users\Adam\scoop\apps\gogdl\current\gogdl.exe --auth-config-path C:\Users\Adam\AppData\Roaming\Playnite\ExtensionsData\03689811-3f33-4dfb-a121-2ee168fb9a5c\tokens.json redist --ids ISI --path / --print-manifest
19-11 09:55:02.996|DEBUG|GogOssLibrary#CliWrapCommandExtensions:Executing command: C:\Users\Adam\scoop\apps\gogdl\current\gogdl.exe --auth-config-path C:\Users\Adam\AppData\Roaming\Playnite\ExtensionsData\03689811-3f33-4dfb-a121-2ee168fb9a5c\tokens.json redist --ids ISI --path C:\Users\Adam\AppData\Roaming\Playnite\ExtensionsData\03689811-3f33-4dfb-a121-2ee168fb9a5c\.gogRedist --max-workers 4 --platform windows --skip-dlcs
19-11 10:16:17.515|DEBUG|GogOssLibrary#CliWrapCommandExtensions:Executing command: C:\Users\Adam\scoop\apps\gogdl\current\gogdl.exe --auth-config-path C:\Users\Adam\AppData\Roaming\Playnite\ExtensionsData\03689811-3f33-4dfb-a121-2ee168fb9a5c\tokens.json redist --ids DirectX --path / --print-manifest
19-11 10:16:32.016|DEBUG|GogOssLibrary#CliWrapCommandExtensions:Executing command: C:\Users\Adam\scoop\apps\gogdl\current\gogdl.exe --auth-config-path C:\Users\Adam\AppData\Roaming\Playnite\ExtensionsData\03689811-3f33-4dfb-a121-2ee168fb9a5c\tokens.json redist --ids nGlide --path / --print-manifest
19-11 10:18:02.608|DEBUG|GogOssLibrary#CliWrapCommandExtensions:Executing command: C:\Users\Adam\scoop\apps\gogdl\current\gogdl.exe --auth-config-path C:\Users\Adam\AppData\Roaming\Playnite\ExtensionsData\03689811-3f33-4dfb-a121-2ee168fb9a5c\tokens.json redist --ids nGlide_103 --path / --print-manifest
19-11 10:18:20.582|DEBUG|GogOssLibrary#CliWrapCommandExtensions:Executing command: C:\Users\Adam\scoop\apps\gogdl\current\gogdl.exe --auth-config-path C:\Users\Adam\AppData\Roaming\Playnite\ExtensionsData\03689811-3f33-4dfb-a121-2ee168fb9a5c\tokens.json redist --ids MSVC2012_x64 --path / --print-manifest
19-11 10:18:21.730|DEBUG|GogOssLibrary#CliWrapCommandExtensions:Executing command: C:\Users\Adam\scoop\apps\gogdl\current\gogdl.exe --auth-config-path C:\Users\Adam\AppData\Roaming\Playnite\ExtensionsData\03689811-3f33-4dfb-a121-2ee168fb9a5c\tokens.json redist --ids MSVC2012 --path / --print-manifest
19-11 10:18:40.952|DEBUG|GogOssLibrary#CliWrapCommandExtensions:Executing command: C:\Users\Adam\scoop\apps\gogdl\current\gogdl.exe --auth-config-path C:\Users\Adam\AppData\Roaming\Playnite\ExtensionsData\03689811-3f33-4dfb-a121-2ee168fb9a5c\tokens.json redist --ids DOSBox074_2CS --path / --print-manifest
19-11 10:20:34.824|DEBUG|GogOssLibrary#CliWrapCommandExtensions:Executing command: C:\Users\Adam\scoop\apps\gogdl\current\gogdl.exe --auth-config-path C:\Users\Adam\AppData\Roaming\Playnite\ExtensionsData\03689811-3f33-4dfb-a121-2ee168fb9a5c\tokens.json redist --ids MSVC2015 --path / --print-manifest
19-11 10:21:04.762|DEBUG|GogOssLibrary#CliWrapCommandExtensions:Executing command: C:\Users\Adam\scoop\apps\gogdl\current\gogdl.exe --auth-config-path C:\Users\Adam\AppData\Roaming\Playnite\ExtensionsData\03689811-3f33-4dfb-a121-2ee168fb9a5c\tokens.json redist --ids MSVC2015_x64 --path / --print-manifest
19-11 10:21:05.899|DEBUG|GogOssLibrary#CliWrapCommandExtensions:Executing command: C:\Users\Adam\scoop\apps\gogdl\current\gogdl.exe --auth-config-path C:\Users\Adam\AppData\Roaming\Playnite\ExtensionsData\03689811-3f33-4dfb-a121-2ee168fb9a5c\tokens.json redist --ids MSVC2017 --path / --print-manifest
19-11 10:21:07.139|DEBUG|GogOssLibrary#CliWrapCommandExtensions:Executing command: C:\Users\Adam\scoop\apps\gogdl\current\gogdl.exe --auth-config-path C:\Users\Adam\AppData\Roaming\Playnite\ExtensionsData\03689811-3f33-4dfb-a121-2ee168fb9a5c\tokens.json redist --ids MSVC2017_x64 --path / --print-manifest
19-11 10:21:08.330|DEBUG|GogOssLibrary#CliWrapCommandExtensions:Executing command: C:\Users\Adam\scoop\apps\gogdl\current\gogdl.exe --auth-config-path C:\Users\Adam\AppData\Roaming\Playnite\ExtensionsData\03689811-3f33-4dfb-a121-2ee168fb9a5c\tokens.json redist --ids UE4REDIST --path / --print-manifest
19-11 10:21:09.689|DEBUG|GogOssLibrary#CliWrapCommandExtensions:Executing command: C:\Users\Adam\scoop\apps\gogdl\current\gogdl.exe --auth-config-path C:\Users\Adam\AppData\Roaming\Playnite\ExtensionsData\03689811-3f33-4dfb-a121-2ee168fb9a5c\tokens.json redist --ids MSVC2019 --path / --print-manifest
19-11 10:21:10.870|DEBUG|GogOssLibrary#CliWrapCommandExtensions:Executing command: C:\Users\Adam\scoop\apps\gogdl\current\gogdl.exe --auth-config-path C:\Users\Adam\AppData\Roaming\Playnite\ExtensionsData\03689811-3f33-4dfb-a121-2ee168fb9a5c\tokens.json redist --ids MSVC2019_x64 --path / --print-manifest
19-11 10:21:40.041|DEBUG|GogOssLibrary#CliWrapCommandExtensions:Executing command: C:\Users\Adam\scoop\apps\gogdl\current\gogdl.exe --auth-config-path C:\Users\Adam\AppData\Roaming\Playnite\ExtensionsData\03689811-3f33-4dfb-a121-2ee168fb9a5c\tokens.json redist --ids PHYSX --path / --print-manifest
19-11 10:23:46.489|DEBUG|GogOssLibrary#CliWrapCommandExtensions:Executing command: C:\Users\Adam\scoop\apps\gogdl\current\gogdl.exe --auth-config-path C:\Users\Adam\AppData\Roaming\Playnite\ExtensionsData\03689811-3f33-4dfb-a121-2ee168fb9a5c\tokens.json redist --ids MSVC2013 --path / --print-manifest
19-11 10:23:47.728|DEBUG|GogOssLibrary#CliWrapCommandExtensions:Executing command: C:\Users\Adam\scoop\apps\gogdl\current\gogdl.exe --auth-config-path C:\Users\Adam\AppData\Roaming\Playnite\ExtensionsData\03689811-3f33-4dfb-a121-2ee168fb9a5c\tokens.json redist --ids MSVC2013_x64 --path / --print-manifest
19-11 10:24:16.475|DEBUG|GogOssLibrary#CliWrapCommandExtensions:Executing command: C:\Users\Adam\scoop\apps\gogdl\current\gogdl.exe --auth-config-path C:\Users\Adam\AppData\Roaming\Playnite\ExtensionsData\03689811-3f33-4dfb-a121-2ee168fb9a5c\tokens.json redist --ids MSVC2010 --path / --print-manifest
19-11 17:25:17.644|DEBUG|GogOssLibrary#CliWrapCommandExtensions:Executing command: C:\Users\Adam\scoop\apps\gogdl\current\gogdl.exe --auth-config-path C:\Users\Adam\AppData\Roaming\Playnite\ExtensionsData\03689811-3f33-4dfb-a121-2ee168fb9a5c\tokens.json redist --ids ISI,MSVC2010 --path C:\Users\Adam\AppData\Roaming\Playnite\ExtensionsData\03689811-3f33-4dfb-a121-2ee168fb9a5c\.gogRedist --max-workers 4 --platform windows --skip-dlcs
19-11 20:57:43.413|DEBUG|GogOssLibrary#CliWrapCommandExtensions:Executing command: C:\Users\Adam\scoop\apps\gogdl\current\gogdl.exe --auth-config-path C:\Users\Adam\AppData\Roaming\Playnite\ExtensionsData\03689811-3f33-4dfb-a121-2ee168fb9a5c\tokens.json redist --ids MSVC2012_x64 --path / --print-manifest
19-11 20:57:44.626|DEBUG|GogOssLibrary#CliWrapCommandExtensions:Executing command: C:\Users\Adam\scoop\apps\gogdl\current\gogdl.exe --auth-config-path C:\Users\Adam\AppData\Roaming\Playnite\ExtensionsData\03689811-3f33-4dfb-a121-2ee168fb9a5c\tokens.json redist --ids MSVC2012 --path / --print-manifest
19-11 20:57:45.779|DEBUG|GogOssLibrary#CliWrapCommandExtensions:Executing command: C:\Users\Adam\scoop\apps\gogdl\current\gogdl.exe --auth-config-path C:\Users\Adam\AppData\Roaming\Playnite\ExtensionsData\03689811-3f33-4dfb-a121-2ee168fb9a5c\tokens.json redist --ids DirectX --path / --print-manifest
19-11 22:17:15.436|DEBUG|GogOssLibrary#CliWrapCommandExtensions:Executing command: C:\Users\Adam\scoop\apps\gogdl\current\gogdl.exe --auth-config-path C:\Users\Adam\AppData\Roaming\Playnite\ExtensionsData\03689811-3f33-4dfb-a121-2ee168fb9a5c\tokens.json redist --ids ISI,MSVC2010 --path C:\Users\Adam\AppData\Roaming\Playnite\ExtensionsData\03689811-3f33-4dfb-a121-2ee168fb9a5c\.gogRedist --max-workers 4 --platform windows --skip-dlcs
```

**Comment by hawkeye116477** [comment]
> To prevent weird queueing edge cases that could occur from manual user interventions and to make the queue less cluttered, GOG Redistributables could be hidden and prepended to the existing game entries instead of discretely listed, but I don't know how easy or hard it'd be to calculate total download size for the progress bar to do it this way or what other complications could occur.

That can't be done currently, because gogdl is done in such way that all depends needs to be downloaded at once.
Initially I wanted to separate each depend, but then gogdl removes other and that's the problem. 
Then I came into idea to ditch gogdl and make own downloading code to do that better, but problem was that performance/speed isn't enough for us, cuz we're still on old .NET.

**Comment by instinctualjealousy** [comment]
> I think big problem might be that gogdl is done in such way that all depends needs to be downloaded as all in one (1 entry only).

I discovered this exact behavior you describe when working with it manually. It appears you need to run `--ids` with the already-installed dependencies in the comma-separated list as well, otherwise they will get removed.

Each time `redist --ids` is called by your plugin for dependency installation, it should gather all currently installed dependencies + any dependencies required by the queued game that aren't installed yet. If gogdl is fed dependencies that are already installed, it skips them with "Nothing to do", but it won't delete them. It does delete existing dependencies not expressly listed when ran with `--ids`, which is the annoyance you describe.

I think using it in this way would make it compatible with per-game `redist` calls.

**Comment by hawkeye116477** [comment]
Ok, you can start testing :smile:.
[GogOssLibrary_1_1_4_36453.pext.zip](https://github.com/user-attachments/files/18013216/GogOssLibrary_1_1_4_36453.pext.zip)

**Comment by instinctualjealousy** [comment]
I'm not sure what the expected result is supposed to be or if I've tested adequately. I downloaded a couple small games that both didn't have dependencies, so I had to dig to see what games I have that do.

I chose Requiem: Avenging Angel. It requires DirectX and nGlide. I deleted DirectX from my `.gogRedist` folder and from `installedDepends.json` (when Playnite wasn't running, of course), then I proceeded to get the download started. DirectX was never downloaded or added to `installedDepends.json`, and I see no evidence in the log of any attempts to install DirectX.

I'll supply any information you need, but I'm not sure if the log as-is can help much here.

**Comment by hawkeye116477** [comment]
>  I deleted DirectX from my .gogRedist folder and from installedDepends.json (when Playnite wasn't running, of course), then I proceeded to get the download started. DirectX was never downloaded or added to installedDepends.json

In that case. It won't be downloaded again, cuz gogdl looks for HGLinstalled at `.gogdl-redist-manifest` file and if it see any of depends listed here, then it won't download again.

**Comment by instinctualjealousy** [comment]
![image](https://github.com/user-attachments/assets/87794eac-ec26-40e4-9a08-4dfca407fa7e)
I fixed it based on your info to get it to pop up. No dependencies were deleted, DirectX was added. Guess this is why you were probing `--print-manifest`.
✨The more you know. 🌠

Command is executed exactly like my recommendation (currently DL'd + need to be DL'd - redundancies):
`05-12 10:03:18.357|DEBUG|GogOssLibrary#CliWrapCommandExtensions:Executing command: C:\Users\Adam\scoop\apps\gogdl\current\gogdl.exe --auth-config-path C:\Users\Adam\AppData\Roaming\Playnite\ExtensionsData\03689811-3f33-4dfb-a121-2ee168fb9a5c\tokens.json redist --ids ISI,DirectX,MSVC2013,MSVC2013_x64,MSVC2015,MSVC2015_x64,MSVC2017,MSVC2017_x64,UE4REDIST,MSVC2019,MSVC2019_x64,MSVC2012_x64,MSVC2012,PHYSX,MSVC2010 --path C:\Users\Adam\AppData\Roaming\Playnite\ExtensionsData\03689811-3f33-4dfb-a121-2ee168fb9a5c\.gogRedist --max-workers 4 --platform windows --skip-dlcs`

If this same operation occurs for every queue entry, I don't think I need to load the queue up to test this... but I can if you think so. Main issue is most GOG games have no dependencies, haha.

**Comment by hawkeye116477** [comment]
> why you were probing --print-manifest

Well, that's to get info about download size :smile:.

Alternatively if will be problems with gogdl during downloading depends then I could do my own downloading code instead of. 
With games problem was that they were splitted into parts, so performance/speed wasn't enough, but depends are rather one, so theoretically I could do that separately :smile:.
