### ISSUE TITLE
Hangs while pulling GOG library after a while and then crashes playnite. Doesnt end up adding anything to playnite library

### ISSUE THREAD

**Issue by nsilvias** [hawkeye116477/playnite-gog-oss-plugin#7]
### Prerequisites

- [X] I've looked through [existing issues](https://github.com/hawkeye116477/playnite-gog-oss-plugin/issues) to make sure that this bug hasn't been reported before.
- [X] I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines) and know netiquette.

### Playnite version

10.34

### Plugin version

1.0.0

### Comet version

0.1.2

### Gogdl version

1.1.2

### Bug description

When attempting to pull GOG library it will hang for a while and then eventually crash Playnite entirely while not adding any new entries to my library. moving existing GOG games in my library to your plugin thru the options for your plugin worked fine tho.
Not sure if it has anything to do with all the of the GOG games i have manually added to Playnites Import Exclusion List with the standard Playnite GOG extension.

### Relevant log

None

**Comment by hawkeye116477** [comment]
I can't reproduce that.

> and then eventually crash Playnite entirely 

Show me playnite.log and/or extension.log file.

**Comment by nsilvias** [comment]
it seems like your update fixed the issue. i can even install games now which i also couldnt do before. good stuff! thank you
