### ISSUE TITLE
Advanced Settings: Custom path for gogdl and comet

### ISSUE THREAD

**Issue by Deide** [hawkeye116477/playnite-gog-oss-plugin#8]
### Prerequisites

- [X] I've looked through [existing issues](https://github.com/hawkeye116477/playnite-gog-oss-plugin/issues) to make sure that this bug hasn't been reported before.
- [X] I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines) and know netiquette.

### Playnite version

10.34.0.23368

### Plugin version

1.0.0.32641

### Comet version

0.1.2

### Gogdl version

1.1.2

### Bug description

I'm using a custom gogdl and comet location, but the extension isn't picking it up. On top of this, the `Gogdl Path` and `Games Installation Path` folder picker buttons don't seem to do anything. I've verified that my installations of gogdl and comet both show the version.

```powershell
λ I:\apps\gogdl\current\gogdl_windows_x86_64.exe --version --auth-config-path I:\apps\playnite\current\ExtensionsData\03689811-3f33-4dfb-a121-2ee168fb9a5c\tokens.json

1.1.2

λ I:\apps\gog-comet\current\comet-x86_64-pc-windows-msvc.exe --version

comet 0.1.2
```

The "raw data" from `Troubleshooting information`:
```json
{
  "PlayniteVersion": "10.34.0.23368",
  "PluginVersion": "1.0.0.32641",
  "CometVersion": "Not%20installed",
  "GogdlVersion": "Not%20installed",
  "CometBinary": "",
  "GogdlBinary": "",
  "GamesInstallationPath": "G:\\Storage\\PC\\GOG"
}
```

It's strange, because it looks just fine in the extension's `config.json`
```json
{
  "ImportInstalledGames": true,
  "ConnectAccount": true,
  "ImportUninstalledGames": true,
  "EnableCometSupport": true,
  "UseVerticalCovers": true,
  "Locale": "en",
  "GamesInstallationPath": "G:\\Storage\\PC\\GOG",
  "SelectedCometPath": "I:\\apps\\gog-comet\\current\\comet-x86_64-pc-windows-msvc.exe",
  "SelectedGogdlPath": "I:\\apps\\gogdl\\current\\gogdl_windows_x86_64.exe",
  "MaxWorkers": 0,
  "UnattendedInstall": false,
  "DownloadAllDlcs": false,
  "DisplayDownloadSpeedInBits": false,
  "DisplayDownloadTaskFinishedNotifications": true,
  "DoActionAfterDownloadComplete": 0,
  "GamesUpdatePolicy": 4,
  "NextGamesUpdateTime": 0,
  "AutoUpdateGames": false,
  "CometUpdatePolicy": 4,
  "NextCometUpdateTime": 0,
  "SyncPlaytime": false,
  "AutoClearCache": 0,
  "NextClearingTime": 0,
  "SyncGameSaves": false
}
```

Couldn't see anything in the `extensions.log` that serves as any kind of elucidation.

It's worth noting that if I put the comet and gogdl binaries in the `{PlayniteDIir}/GOG OSS` directory, it seems to register it just fine.

### Relevant log

No relevant logs to show

**Comment by hawkeye116477** [comment]
Thanks for report. Looks like I forgot about checking that and button functions aren't implemented, while custom paths have small bug.
